config/routes.rb
Rails.application.routes.draw do
  resources :likes

  devise_for :users
  root 'movies#index'


  resources :directors
  resources :actors
  resources :roles
  resources :movies

  get '/my_favorites' => 'movies#favorites'
end

app/models/actor.rb
class Actor < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true

  # has many Roles (method name: "roles", foreign key: actor_id)

  # def roles
  #   return Role.where({ :actor_id => self.id })
  # end

  has_many :roles

  # Challenge:
  # has many Movies (method name: "filmography")

  # def filmography
  #   return Movie.where :id => self.roles.pluck(:movie_id)
  # end

  has_many :filmography, :through => :roles, :source => :movie
end

app/models/director.rb
class Director < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true

  has_many :filmography, :class_name => "Movie", :foreign_key => "director_id"

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user, :presence => true, :uniqueness => { :scope => :movie }
  validates :movie, :presence => true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validates :title, :presence => true

  belongs_to :director

  has_many :roles, :dependent => :destroy, :dependent => :destroy

  has_many :cast, :through => :roles, :source => :actor

  has_many :likes

  has_many :users, :through => :likes
end

app/models/role.rb
class Role < ActiveRecord::Base
  validates :character_name, :presence => true
  validates :movie_id, :presence => true
  validates :actor_id, :presence => true

  # belongs to Actor (method name: "actor", foreign key: actor_id)

  # def actor
  #   return Actor.find_by({ :id => self.actor_id })
  # end

  belongs_to :actor, :class_name => "Actor", :foreign_key => "actor_id"


  # belongs to Movie (method name: "movie", foreign key: movie_id)

  # def movie
  #   return Movie.find_by({ :id => self.movie_id })
  # end

  belongs_to :movie, :class_name => "Movie", :foreign_key => "movie_id"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :likes

  has_many :movies, :through => :likes
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  def index
    @actors = Actor.all
  end

  def show
  end

  def new
    @actor = Actor.new
  end

  def create
    @actor = Actor.new(actor_params)

    if @actor.save
      redirect_to actors_url, :notice => "Actor created successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @actor.update(actor_params)

    if @actor.save
      redirect_to actor_url(@actor.id), :notice => "Actor updated successfully."
    else
      render 'edit'
    end
  end

  def destroy


    @actor.destroy

    redirect_to actors_url, :notice => "Actor deleted."
  end

  private

  def set_actor
    @actor = Actor.find(params[:id])
  end

  def actor_params
    params.require(:actor).permit(:dob, :name, :bio, :image_url)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]



  def index
    @directors = Director.all

    respond_to do |format|
      format.html { render 'index'}
      format.json { render json: @directors }
    end
  end

  def show

    respond_to do |format|
      format.html { render 'show'}
      format.json { render json: @director }
    end
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(director_params)

    if @director.save
      redirect_to directors_url, :notice => "Director created successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @director.update(director_params)

    if @director.save
      redirect_to director_url(@director.id), :notice => "Director updated successfully."
    else
      render 'edit'
    end
  end

  def destroy

    @director.destroy

    redirect_to directors_url, :notice => "Director deleted."
  end

  private

  def set_director
    @director = Director.find(params[:id])
  end

  def director_params
    params.require(:director).permit(:dob, :name, :bio, :image_url)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)
    @like.user = current_user

    respond_to do |format|
      if @like.save
        format.html { redirect_to :back, notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:user_id, :movie_id)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def favorites

  end

  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_url, :notice => "Movie created successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @movie.update(movie_params)

    if @movie.save
      redirect_to movie_url(@movie.id), :notice => "Movie updated successfully."
    else
      render 'edit'
    end
  end

  def destroy

    @movie.destroy

    redirect_to movies_url, :notice => "Movie deleted."
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :year, :duration, :description, :image_url, :director_id)
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  def index
    @roles = Role.all
  end

  def show
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    if @role.save
      redirect_to roles_url, :notice => "Role created successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @role.update(role_params)

    if @role.save
      redirect_to role_url(@role.id), :notice => "Role updated successfully."
    else
      render 'edit'
    end
  end

  def destroy

    @role.destroy

    redirect_to roles_url, :notice => "Role deleted."
  end

  private

  def set_role
    @role = Role.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:character_name, :movie_id, :actor_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/actors/edit.html.erb
<!-- Validation failure messages -->

<% if @actor.errors.any? %>
  <% @actor.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>



<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Actor #<%= @actor.id %></h3>
      </div>
      <div class="panel-body">
       <%= form_for @actor, :html => { :class => "form-horizontal" } do |f| %>
         <!-- Label and input for dob -->
         <div class="form-group">
           <%= f.label :dob, class: "col-sm-2 control-label" %>
           <div class="col-sm-10">
             <%= f.text_field :dob, placeholder: "Dob", class: "form-control" %>
           </div>
         </div>

         <!-- Label and input for name -->
         <div class="form-group">
           <%= f.label :name, class: "col-sm-2 control-label" %>
           <div class="col-sm-10">
             <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
           </div>
         </div>

         <!-- Label and input for bio -->
         <div class="form-group">
           <%= f.label :bio, class: "col-sm-2 control-label" %>
           <div class="col-sm-10">
             <%= f.text_field :bio, placeholder: "Bio", rows: "3", class: "form-control" %>
           </div>
         </div>

         <!-- Label and input for image_url -->
         <div class="form-group">
           <%= f.label :image_url, class: "col-sm-2 control-label" %>
           <div class="col-sm-10">
             <%= f.text_field :image_url, placeholder: "Image url", class: "form-control" %>
           </div>
         </div>

         <div class="form-group">
           <div class="col-sm-offset-2 col-sm-10">
             <%= f.submit class: "btn btn-success" %>
             or
             <a href="/actors">Cancel</a>
           </div>
         </div>
       <% end %>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

app/views/actors/index.html.erb
<div class="page-header">
  <h1>
    Actors
    <%= link_to new_actor_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Simple table layout example -->

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Dob</th>
          <th>Name</th>
          <th>Bio</th>
          <th>Image url</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @actors.each do |actor| %>
          <tr>
            <td><%= actor.dob %></td>
            <td><%= actor.name %></td>
            <td><%= actor.bio %></td>
            <td><%= actor.image_url %></td>
            <td>
              <%= link_to actor_url(actor), :class => "btn btn-primary" do %>
                <i class="fa fa-search-plus"></i>
              <% end %>
            </td>
            <td>
              <%= link_to edit_actor_url(actor), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
            </td>
            <td>
              <%= link_to actor_url(actor), :method => "delete", :data => { :confirm => "Do you really want to delete this actor?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- End simple table layout example -->

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Actors (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @actors.each do |actor| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Actor #<%= actor.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Dob</dt>
          <dd><%= actor.dob %></dd>

          <dt>Name</dt>
          <dd><%= actor.name %></dd>

          <dt>Bio</dt>
          <dd><%= actor.bio %></dd>

          <dt>Image url</dt>
          <dd><%= actor.image_url %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to actor_url(actor), :class => "btn btn-primary" do %>
            <i class="fa fa-search-plus"></i>
          <% end %>
          <%= link_to edit_actor_url(actor), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to actor_url(actor), :method => "delete", :data => { :confirm => "Do you really want to delete this actor?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container').isotope({
      itemSelector: '.isotope-item',
      layoutMode: 'masonry',
      filter: function() {
        return qsRegex ? $(this).text().match( qsRegex ) : true;
      }
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/actors/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Actor #<%= @actor.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Dob</dt>
              <dd><%= @actor.dob %></dd>

              <dt>Name</dt>
              <dd><%= @actor.name %></dd>

              <dt>Bio</dt>
              <dd><%= @actor.bio %></dd>

              <dt>Image url</dt>
              <dd><%= @actor.image_url %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to actors_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_actor_url(@actor.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to actor_url(@actor.id), :method => "delete", :data => { :confirm => "Do you really want to delete this actor?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/directors/_zebra.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Director #<%= director.id %></h3>
    </div>
    <div class="panel-body">
      <%= link_to image_tag(director.image_url), director_url(director.id), :class => "thumbnail" %>
      <dl>
        <dt>Name</dt>
        <dd><%= director.name %></dd>

        <dt>Dob</dt>
        <dd><%= director.dob %></dd>
      </dl>
      <div class="btn-group btn-group-justified">
        <%= link_to director, :class => "btn btn-primary" do %>
          <i class="fa fa-search-plus"></i>
        <% end %>
        <%= link_to edit_director_url(director), :class => "btn btn-warning" do %>
          <i class="fa fa-edit"></i>
        <% end %>
        <%= link_to director, :method => "delete", :data => { :confirm => "Do you really want to delete this director?" }, :class => "btn btn-danger" do %>
          <i class="fa fa-trash-o"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/directors/index.html.erb
<div class="page-header">
  <h1>
    Directors
    <%= link_to new_director_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Directors (start typing)" class="form-control">
  </div>
</div>

<hr>

<%= render 'form', :director => Director.new %>


<div class="row isotope-container">
<% @directors.each do |elephant| %>
  <%= render('zebra', { :director => elephant })  %>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container').isotope({
      itemSelector: '.isotope-item',
      layoutMode: 'masonry',
      filter: function() {
        return qsRegex ? $(this).text().match( qsRegex ) : true;
      }
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/directors/show.html.erb
<%= render('zebra', :director => @director) %>

<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Director #<%= @director.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Dob</dt>
              <dd><%= @director.dob %></dd>

              <dt>Name</dt>
              <dd><%= @director.name %></dd>

              <dt>Bio</dt>
              <dd><%= @director.bio %></dd>

              <dt>Image url</dt>
              <dd><%= @director.image_url %></dd>
            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to directors_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_director_url(@director.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to director_url(@director.id), :method => "delete", :data => { :confirm => "Do you really want to delete this director?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% @director.filmography.each do |movie| %>
  <%= render 'movies/movie', :movie => movie %>
<% end %>

<!-- End responsive panel example -->

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :email %>
  </div>
  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.collection_select :movie_id, Movie.all, :id, :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Likes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.user.email %></td>
        <td><%= like.movie.title %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @like.user %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @like.movie %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>

app/views/movies/_movie.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Movie #<%= movie.id %> (<%= movie.likes.count %>)</h3>
    </div>
    <div class="panel-body">
      <%#= link_to image_tag(movie.image_url), movie, :class => "thumbnail" %>

      <dl>
        <dt>Title</dt>
        <dd><%= movie.title %></dd>

        <dt>Year</dt>
        <dd><%= movie.year %></dd>

        <dt>Duration</dt>
        <dd><%= movie.duration %></dd>

        <dt>Description</dt>
        <dd><%= movie.description %></dd>

        <dt>Director</dt>
        <dd>
          <%= movie.director.try(:name) %>
        </dd>

      </dl>
      <div class="btn-group btn-group-justified">
        <%= link_to movie_url(movie), :class => "btn btn-primary" do %>
          <i class="fa fa-search-plus"></i>
        <% end %>
        <%= link_to edit_movie_url(movie), :class => "btn btn-warning" do %>
          <i class="fa fa-edit"></i>
        <% end %>
        <%= link_to movie_url(movie), :method => "delete", :data => { :confirm => "Do you really want to delete this movie?" }, :class => "btn btn-danger" do %>
          <i class="fa fa-trash-o"></i>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <% like = Like.find_by({ :user_id => current_user.id, :movie_id => movie.id }) %>
        <% if like.present? %>
          <%= link_to 'Unlike', like_url(like.id), :method => :delete, :class => "btn btn-warning" %>
        <% else %>
          <%= form_for Like.new :user => current_user, :movie => movie do |f| %>
            <%= f.hidden_field :movie_id %>

            <%= f.submit :class => "btn btn-success" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/roles/index.html.erb
<div class="page-header">
  <h1>
    Roles
    <%= link_to new_role_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Simple table layout example -->

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Character name</th>
          <th>Movie</th>
          <th>Actor</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @roles.each do |role| %>
          <tr>
            <td><%= role.character_name %></td>
            <td><%= role.movie.title %></td>
            <td><%= role.actor.name %></td>
            <td>
              <%= link_to role_url(role), :class => "btn btn-primary" do %>
                <i class="fa fa-search-plus"></i>
              <% end %>
            </td>
            <td>
              <%= link_to edit_role_url(role), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
            </td>
            <td>
              <%= link_to role_url(role), :method => "delete", :data => { :confirm => "Do you really want to delete this role?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- End simple table layout example -->

app/views/roles/show.html.erb
<!-- Simple full-width example-->

<div class="page-header">
  <h1>Role #<%= @role.id %></h1>
</div>

<div class="row">
  <div class="col-md-12">
    <dl class="dl-horizontal">
      <dt>Character name</dt>
      <dd><%= @role.character_name %></dd>

      <dt>Movie</dt>
      <dd><%= Movie.find(@role.movie_id).title %></dd>

      <dt>Actor</dt>
      <dd><%= Actor.find(@role.actor_id).name %></dd>

      <dt></dt>
      <dd>
        <div class="btn-group">
          <%= link_to roles_url, :class => "btn btn-primary" do %>
            <i class="fa fa-chevron-left"></i>
          <% end %>
          <%= link_to edit_role_url(@role.id), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to role_url(@role.id), :method => "delete", :data => { :confirm => "Do you really want to delete this role?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </dd>
    </dl>

  </div>
</div>

<!-- End simple full-width example-->

<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Role #<%= @role.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Character name</dt>
              <dd><%= @role.character_name %></dd>

              <dt>Movie</dt>
              <dd><%= @role.movie_id %></dd>

              <dt>Actor</dt>
              <dd><%= @role.actor_id %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to roles_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_role_url(@role.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to role_url(@role.id), :method => "delete", :data => { :confirm => "Do you really want to delete this role?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->